/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

/**
 *
 * @author Sufiyan Mohammad
 * MasterMind is a class 
 */

public class MasterMind {
    
    private Attempt secretCode;
    private Attempt essay; 
    private boolean success;
    
    /**
     *
     */
    public MasterMind(){
    
        this.secretCode = new Attempt(); 
        this.essay = new Attempt();
        this.success = false;
    }
    
    /**
    *This constructor creates the mastermind
    * 
    * @param secretCode : this is the answer that you are supposed to find. The code is generated by the the computer.
    * 
    */
    public MasterMind(Attempt secretCode) {
        
        this.secretCode = secretCode; 
        this.essay = new Attempt();
        this.success = false;
    
    }
    
    /**
     *
     * @param secretCode
     * @param essay : is the user trial.
     */
    public MasterMind(Attempt secretCode, Attempt essay ) {
        

        this.secretCode = secretCode; 
        this.essay = essay;
        this.success = false;
    
    }  
   
    /**
     *
     * @param secretCode
     * @param success : Validates user input.
     */
    public MasterMind(Attempt secretCode, boolean success ) {
        
        this.secretCode = secretCode; 
        this.essay = new Attempt();
        this.success = false;
    
    }  
  /*
    This consdtructor
    @param secretCode 
    
    */

    /**
     *
     * @param secretCode
     * @param essay
     * @param success
     */

    public MasterMind(Attempt secretCode, Attempt essay, boolean success) {
        
        this.secretCode = secretCode; 
        this.essay = essay;
        this.success = success;
    
    }   
    
    /**
     *
     * @return
     */
    public Attempt getSecretCode(){
    
        return secretCode;
    }
    
    /**
     *
     * @return
     */
    public Attempt getEssay(){
    
        return essay;
    }

    /**
     *
     * @return
     */
    public boolean getSuccess(){
    
        return success;
    }
    
    /**
     *
     * @param secretCode
     */
    public void setSecretCode(Attempt secretCode){
    
        this.secretCode = secretCode;
    }
    
    /**
     *
     * @param essay
     */
    public void setEssay(Attempt essay){
    
        this.essay = essay;
    }
    
    /**
     *
     * @param success
     */
    public void getSuccess(boolean success){
    
        this.success = success;
    }
    
    /**
     *
     * @return
     */
    public boolean comparison(){
        
        int goodAnswer = 0;
        int badAnswer = 0;
        int codeLength = secretCode.getLength();
        String[] myEssay = essay.getCombination();
        String[] mySecretCode = secretCode.getCombination();
        
        //Inserrtion 
        for(int i = 0; i < codeLength; i++){
                
            if (myEssay[i].equals(mySecretCode[i]) == true){   

                
                goodAnswer++;
            }
            else{
                badAnswer++;
            }    
        } 
        
        System.out.println("[" + goodAnswer + "-" + badAnswer + "]");
        
        if (badAnswer == 0){
            success = true;
        }
        
        return success;
        

        
    }
}
